"""
This type stub file was generated by pyright.
"""

import importlib.metadata
from .client import Client, MessageType
from .errors import ClientNotConnectedError, IncorrectPasswordError, RCONConnectionError

__version__ = ...
__all__ = ("MessageType", "Client", "RCONConnectionError", "ClientNotConnectedError", "IncorrectPasswordError", "__version__")
