"""
This type stub file was generated by pyright.
"""

import enum
import typing as t

class MessageType(enum.IntEnum):
    LOGIN = ...
    COMMAND = ...
    RESPONSE = ...


class Client:
    """The base class for creating an RCON client."""
    def __init__(self, host: str, port: int, password: str) -> None:
        ...
    
    async def __aenter__(self, timeout=...) -> Client:
        ...
    
    async def __aexit__(self, exc_type: type, exc: Exception, tb: t.Any) -> None:
        ...
    
    async def connect(self, timeout: float = ...) -> None:
        """Sets up the connection between the client and server."""
        ...
    
    async def send_cmd(self, cmd: str, timeout: float = ...) -> tuple[str, int]:
        """Sends a command to the server."""
        ...
    
    async def close(self) -> None:
        """Closes the connection between the client and the server."""
        ...
    


