"""
This type stub file was generated by pyright.
"""

class RCONConnectionError(Exception):
    """Raised when the Client.connect() method fails."""
    def __init__(self, msg: str | None = ..., error: Exception | None = ...) -> None:
        ...
    


class ClientNotConnectedError(Exception):
    """Raised when an IO method is used when the Client isn't connected."""
    def __init__(self) -> None:
        ...
    


class IncorrectPasswordError(Exception):
    """Raised when the RCON authentication / password is incorrect."""
    def __init__(self) -> None:
        ...
    


